// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "princessd":return img`
........................
........................
........5.55.5..........
........535535..........
........555555..........
........ffffff..........
.......feeeeeef.........
......feeeeeeeef........
......feeffffeef........
......feffddffef........
.....fefdfddfdfef.......
.....fefd3dd3dfef.......
.....feefddddfeef.......
....feef3ffff3feef......
.....ffd353353dff.......
.....fddf3553fddf.......
......ff333333ff........
......f33333333f........
......ffffffffff........
........ff..ff..........
........................
........................
........................
........................
`;
            case "image2":
            case "princess":return img`
. . . . . . . 5 . 5 . . . . . . 
. . . . . . f 5 3 5 f . . . . . 
. . . . . f e 5 5 5 e f . . . . 
. . . . f e e e e e e e f . . . 
. . . . f e e e e e e e f . . . 
. . . . f e e e e d f d f . . . 
. . . f f e e e e d f d f . . . 
. . f e f e e e d d 3 d f . . . 
. . . f f e f f d d d f . . . . 
. . f e e e f 3 5 f f . . . . . 
. . . f f f f f 3 3 5 f . . . . 
. . . . . . f d f 3 3 f . . . . 
. . . . . . f d f 3 f . . . . . 
. . . . . f d f 3 3 3 f . . . . 
. . . . . . f f 3 3 f f . . . . 
. . . . . . . f f f . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
